# Generated by Django 5.2.4 on 2025-07-09 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('quiz_image', models.TextField(blank=True, null=True)),
                ('quiz_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_list', models.JSONField(blank=True, null=True)),
                ('user_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'quiz',
            },
        ),
    ]
