# Generated by Django 5.2.4 on 2025-07-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz_answer',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='user_answer',
            new_name='selected',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_correct',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
